# web title
title: cayman vb dark

# web desription
description: cayman vb dark theme for jekyll and github pages

# Header buttons for downloads from github repo
#show_downloads: true

# Header buttons link to github repo 
show_github: true

# Header buttons for google analytics 
google_analytics:

# web PNG favicon
favicon: assets/img/osowoso.png

# Theme supports custom buttons
buttons:
  - text: oSoWoSo
    href: https://osowoso.xyz

# Icon shown in header. From Fontawesome https://fontawesome.com/icons?m=free
#icon: fas fa-pencil-alt

# Colour gradient for the header
header-colours: 
  right: "#295340"
  left: "#ABC2AB"
