on: push
jobs:
  build:
    runs-on: ubuntu-latest
    name: script/cibuild
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby
      
      - name: build
        run: script/bootstrap --incremental --trace --watch
      - name: test
        run: script/cibuild --incremental --watch
