on: push
jobs:
  build:
    runs-on: ubuntu-latest
    name: script/cibuild
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1

      - name: build
        run: script/bootstrap --trace --incremental
      - name: test
        run: script/cibuild --trace --incremental

